- name: Create user tomcat
  ansible.builtin.user:
    name: tomcat
  register: app_user

- name: Remove app location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: create app location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: directory


- name: Download & Extract Tomcat Component Archive
  ansible.builtin.unarchive:
    src: curl -s https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.23/bin/apache-tomcat-10.0.23.tar.gz
    dest: "{{ APP_LOCATION }}"
    remote_src: yes

- name: Get Latest Version of Appication from Nexus
  ansible.builtin.shell: curl -s http://44.192.110.235:8081/repository/integration-local/com/javacodegeeks/SampleWebApplication/1.0-SNAPSHOT/SampleWebApplication-1.0-20220717.133631-2.war
  register: out
  args:
    chdir: "{{ APP_LOCATION }}/webapps"

- name: Run Tomcat
  shell: ./startup.sh
  args:
    chdir: "{{ APP_LOCATION }}/apache-tomcat-10.0.23/bin"



