- name: Create user tomcat
  ansible.builtin.user:
    name: tomcat
  register: app_user

- name: Remove app location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: create app location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: directory

- name: Download Tomcat package
  ansible.builtin.shell: wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.23/bin/apache-tomcat-10.0.23.tar.gz "--no-check-certificate"
  register: out
  args:
      chdir: "{{ APP_LOCATION }}"

- name: untar Tomcat package
  ansible.builtin.shell: tar -xvf apache-tomcat-10.0.23.tar.gz
  register: out
  args:
      chdir: "{{ APP_LOCATION }}"

- name: Get Latest Version of Appication from Nexus
  ansible.builtin.shell: wget http://3.228.9.176:8081/repository/integration-local/com/javacodegeeks/SampleWebApplication/1.0-SNAPSHOT/SampleWebApplication-1.0-20220717.133631-2.war "--no-check-certificate"
  register: out
  args:
    chdir: "{{ APP_LOCATION }}/apache-tomcat-10.0.23/webapps"


- name: Download Java JRE
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.rpm
    dest: /opt/jre-8u60-linux-x64.rpm
    headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'

- name: install Java JRE rpm from a local file
  yum:
    name: /opt/jre-8u60-linux-x64.rpm
  state: present

- name: Run Tomcat
  shell: ./startup.sh
  args:
    chdir: "{{ APP_LOCATION }}/apache-tomcat-10.0.23/bin"



